# Copyright 2019 OpenStack Foundation.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Add soft delete for floating IP reservation

Revision ID: afd0a1c7748a
Revises: f4084140f608
Create Date: 2019-03-28 14:14:46.125239

"""

# revision identifiers, used by Alembic.
revision = 'afd0a1c7748a'
down_revision = 'f4084140f608'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('floatingip_allocations',
                  sa.Column('deleted', sa.String(length=36), nullable=True))
    op.add_column('floatingip_allocations',
                  sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('floatingip_reservations',
                  sa.Column('deleted', sa.String(length=36), nullable=True))
    op.add_column('floatingip_reservations',
                  sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('required_floatingips',
                  sa.Column('deleted', sa.String(length=36), nullable=True))
    op.add_column('required_floatingips',
                  sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('required_floatingips', 'deleted_at')
    op.drop_column('required_floatingips', 'deleted')
    op.drop_column('floatingip_reservations', 'deleted_at')
    op.drop_column('floatingip_reservations', 'deleted')
    op.drop_column('floatingip_allocations', 'deleted_at')
    op.drop_column('floatingip_allocations', 'deleted')
    # ### end Alembic commands ###
