- project:
    queue: blazar
    templates:
      - check-requirements
      - openstack-cover-jobs
      - openstack-python3-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - blazar-tempest-plugin-base
        - blazar-tempest-plugin-ipv6-only
        - openstack-tox-pylint:
            voting: false
    gate:
      jobs:
        - blazar-tempest-plugin-base
        - blazar-tempest-plugin-ipv6-only
